# Generated by Django 5.0 on 2024-02-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(default='', max_length=70)),
                ('book', models.CharField(default='', max_length=70)),
                ('jang', models.CharField(default='', max_length=70)),
                ('ki', models.TextField(default='', max_length=256)),
            ],
            options={
                'db_table': 'bible',
            },
        ),
        migrations.CreateModel(
            name='Bible_jang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(default='', max_length=70)),
                ('book', models.CharField(default='', max_length=70)),
                ('jang', models.CharField(default='', max_length=70)),
                ('ki', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'bible_jang',
            },
        ),
        migrations.CreateModel(
            name='BibleEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorteng', models.CharField(default='', max_length=70)),
                ('booengk', models.CharField(default='', max_length=70)),
                ('jangeng', models.CharField(default='', max_length=70)),
                ('kieng', models.TextField(default='', max_length=256)),
            ],
            options={
                'db_table': 'bibleeng',
            },
        ),
    ]
